import React from 'react';
import type { Metadata } from 'next';
import './globals.css'; // Assuming you might have or will create this

export const metadata: Metadata = {
  title: 'EngineUp App',
  description: 'Generated by create next app (or similar)',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
} 